apiVersion: v1
kind: Namespace
metadata:
  name: crshaloop
  annotations:
    "namespace-cleaner/delete": "true"
    "namespace-cleaner/delete-if-has-crashlooping-pods": "true"
    "namespace-cleaner/crashlooping-pods-toleration-hours": "1"

---
# crashlooping pod
apiVersion: v1
kind: Pod
metadata:
  name: crashlooping
  namespace: crshaloop
spec:
    containers:
    - name: crashlooping
      image: busybox
      command: ["/bin/sh", "-c", "exit 1"]
    restartPolicy: Always